### ISSUE TITLE
Duplicated Files?

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1954]
I updated to latest from 1.81b to 1.81e2 and this came up. I tried deleting one of them alternately and an error of map instance pops up.

These are the duplicated files upon updating:
![image](https://user-images.githubusercontent.com/118698151/226524863-4ca7544d-43fb-40fc-8608-49550a191280.png)

These are the errors:
![image](https://user-images.githubusercontent.com/118698151/226524953-039f2570-06f3-4394-aeaa-553517c5ea03.png)

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/147-how-to-update-to-new-version

**Comment by AsheshPlays** [comment]
@insthync I already did that steps. I deleted everything on the list, then imported the kit, also deleted these 3 files for 2021.3:

Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/System.Buffers.dll
Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/System.Memory.dll
Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/System.Threading.Tasks.Extensions.dll

Imported the 2021 Fix. Then  these errors come up after importing the 2021 FIX:

This is what i downloaded from your fix.
MMORPG_KIT2021.2_Microsoft.Bcl.AsyncInterfaces5.0.0.dll.unitypackage

All the steps I followed when updating are same as before. They had no errors except for this recent update.

**Comment by insthync** [comment]
I don't trust you, if you do follow what I told you then the `Assets/UnityMultiplayerARPG/MMO/Scripts` folder will be deleted before importing.

**Comment by AsheshPlays** [comment]
@insthync 

Yes, its part of the deletion.

![image](https://user-images.githubusercontent.com/118698151/226550971-c38851c7-660e-4b99-a538-518ab6470b41.png)

Here is part of the screenshot of what  I deleted. Scripts forlder was included.

**Comment by insthync** [comment]
So should I access your PC with AnyDesk to show you again?

**Comment by AsheshPlays** [comment]
@insthync 

This is the error that is left after reimporting the whole kit again.

Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Networking\Map\MapNetworkManager.cs(809,13): error CS0103: The name 'instanceMapCurrentLocations' does not exist in the current context

Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Networking\Map\MapNetworkManager.cs(810,13): error CS0103: The name 'instanceMapCurrentLocations' does not exist in the current context

**Comment by insthync** [comment]
So it has no duplicating codes issues (Yes, it must not).

About that error I've fixed it, Update to 1.81f or changes codes following this commit https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/7b568a220edb75f5ec8e52322d9554c4eb7249ca

**Comment by AsheshPlays** [comment]
@insthync 

I'll just add it here. So, since the update I only tried building the APK now and I got this error when building the APK. I tried adding a checkmark on android on the sqlite assembly but still the same. 

![image](https://user-images.githubusercontent.com/118698151/226974126-da4f4717-0eab-4881-bb8b-e905bc6adaf1.png)

**Comment by insthync** [comment]
You should create a new post because this one is not relates to duplicating source codes files at all
