### ISSUE TITLE
[BUG] accounts can't login

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#1980]
some accounts are no longer able to log in after restarting the server, it takes a while to load on the character selection screen and then it displays request time out and even updating the version or restarting the server again the problem continues and players have to create another account
![Sem título](https://user-images.githubusercontent.com/106054872/229260014-3a8f20bc-3e4f-4d0b-8935-327767aea6f5.png)

**Comment by RafaelRBizachi** [comment]
this is an account that had 2 characters and after the error none appear, and if you try to create a new one, the error appears again
![image](https://user-images.githubusercontent.com/106054872/229260136-2d171198-c4ff-40b0-b4fe-db7ea2ba0d47.png)

**Comment by insthync** [comment]
Did you use any addons

**Comment by RafaelRBizachi** [comment]
no, I'm using the default login system

**Comment by insthync** [comment]
No I saw it can login, but seems like it is having problems with your character data, so I asked because I want to know that did you use any addons for character data?

**Comment by RafaelRBizachi** [comment]
no, i'm not using any addon all i have is the kit itself, the only things i have outside the mmorpg kit are 3d models and an AI system for some NPCs to walk but all this is done by the client and it always worked normally and i didn't do any change in character data too

**Comment by RafaelRBizachi** [comment]
This only happens with some accounts and it's usually after I restart the server.

**Comment by insthync** [comment]
I want to see all server logging messages.

**Comment by RafaelRBizachi** [comment]
sorry for the delay, in my country it was already late at night. Which of these log files do I need to send?
![Sem título7](https://user-images.githubusercontent.com/106054872/229295274-babdfc60-5714-4e23-afec-aefe4972e2f9.png)

**Comment by insthync** [comment]
All

**Comment by RafaelRBizachi** [comment]
ok, I'll send you a folder with all the logs because it's a little big, just a minute

**Comment by RafaelRBizachi** [comment]
ok, I'll send you a folder with all the logs because it's a little big, just a minute

**Comment by RafaelRBizachi** [comment]
Is there a website you prefer that I upload the log folder to? for some reason the log folder exceeded 3gb, or if you prefer, I can use anydesk for you to take a look, I already have the server with filezilla and the database open on the pc

**Comment by insthync** [comment]
Try send only files with its name contians "Database"

**Comment by RafaelRBizachi** [comment]
I uploaded it to google drive because one of the files exceeded 70mb 
https://drive.google.com/drive/folders/13N8tB8773MaU9a_NLAXZ14HCF2i5IfNa?usp=sharing

**Comment by RafaelRBizachi** [comment]
another problem that may have something to do with this is that after an average of 2 days with the server on, it starts to cause lag and disk usage goes to 1.2gb 100% usage and only resolves by restarting and using nohup again, and sometimes after restarting some account it stops working.

**Comment by insthync** [comment]
Which version are you using?, I found the duplicating `summonbuffs`'s `ID` in the log file, but this one was fixed.

Another problem is MySQL password, as I saw the error message "Authentication method 'caching_sha2_password'"

**Comment by insthync** [comment]
You may try change mysql connection string codes in `MySqlDatabase.cs` -> function `GetConnectionString()`

```
        public string GetConnectionString()
        {
            string connectionString = "Server=" + address + ";" +
                "Port=" + port + ";" +
                "Uid=" + username + ";" +
                (string.IsNullOrEmpty(password) ? "" : "Pwd=\"" + password + "\";") +
                "Database=" + dbName + ";" +
                "SSL Mode=Required;AllowPublicKeyRetrieval=true;";
            return connectionString;
        }
```
Then rebuild/upload server files 
More detail: https://mysqlconnector.net/troubleshooting/retrieval-public-key/

**Comment by RafaelRBizachi** [comment]
from Unity is version 2020.3.31f1 and from Kit and from kit was using version 1.80d until last week, and from this week version 1.81h but the error continues.
I also never deleted the log folder since the beginning of the server.
The authentication method is using the Admin user and the digital ocean password, because with the root user it was causing authentication problems.
I will try to change these lines of code that you presented above to test

**Comment by insthync** [comment]
Then you should try delete all data from `summonbuffs` table, it will remove all buffs that applied to monsters, so you may not worry about it, you can delete log files then try again so you will be able to find an error easily.

**Comment by RafaelRBizachi** [comment]
I tried changing the code line, deleted the SummonBuffs and did the server rebuild but the locked accounts are still unable to recover character information :(

**Comment by RafaelRBizachi** [comment]
![teste](https://user-images.githubusercontent.com/106054872/229312016-2ff0fb6c-c604-4d1c-a80f-3c68bf31787d.png)

**Comment by RafaelRBizachi** [comment]
https://drive.google.com/drive/folders/1BkUmPO7lXFGlDkEg89yURiutFE-Kbfe-?usp=sharing  link with new log errors

**Comment by RafaelRBizachi** [comment]
![teste2](https://user-images.githubusercontent.com/106054872/229315565-832ff5c3-3ce1-4eeb-a9dc-a7d88beb2fd3.png)

**Comment by insthync** [comment]
Send me your AnyDesk address to my email: ittipon.bay@gmail.com, I will check it.

**Comment by RafaelRBizachi** [comment]
ok just a minute I'm changing the version of the kit and I'll send you the anydesk IP

**Comment by RafaelRBizachi** [comment]
I already sent the anydesk ip, the server and the digital ocean are open, feel free

**Comment by RafaelRBizachi** [comment]
I sent one of the accounts that are locked for you to test

**Comment by RafaelRBizachi** [comment]
Thanks for the support
