### ISSUE TITLE
Skill buff rate problem.

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2281]
When I increase normally, there is no problem, but when I increase the percentage, nothing happens.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/adbf4086-bf8a-4d5f-9958-455186b30a9b)

**Comment by insthync** [comment]
Fixed, wait the next version

**Comment by CLAXES** [comment]
When will the new version be shared

**Comment by insthync** [comment]
Don't know

**Comment by CLAXES** [comment]
working on the new version increases others but still doesn't affect speed.

**Comment by insthync** [comment]
Which speed?

**Comment by CLAXES** [comment]
The move speed part here has no effect in the game.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/67eb22f3-0bbf-4b6a-87bf-b6a66cd0ed6a)

**Comment by CLAXES** [comment]
the character does not accelerate when I press buff.

**Comment by CLAXES** [comment]
Have you checked?

**Comment by insthync** [comment]
Yes, it was fixed
